close all;
clear all;
format compact; format long;
addpath(genpath('../../../../../lib/matlab/')) % lib codes

% change directory to the srouce code directory
filePath = mfilename('fullpath');
[scriptPath,fileName,fileExt] = fileparts(filePath); cd(scriptPath); % Change working directory to source code directory.
cd(scriptPath); % Change working directory to source code directory.

kfac = "kfacOneThird";
inPath = "../../build/winx64/intel/19.0.4.245/release/static/heap/serial/fortran/" + kfac;
outDir = fullfile("out",kfac);
mkdir(outDir)

Zmodel.ID = ["H06","B10","M17","F18"];
Zmodel.count = length(Zmodel.ID);

for imodel = 1:Zmodel.count
    Zmodel.(Zmodel.ID(imodel)) = importdata(fullfile(inPath,Zmodel.ID(imodel),"bin","out","batse_zstat.txt"));
    Zmodel.(Zmodel.ID(imodel)).data = sortrows(Zmodel.(Zmodel.ID(imodel)).data,1);
end
ngrb = length(Zmodel.(Zmodel.ID{1}).data(:,1));
LaTab = cell(ngrb,1);
for igrb = 1:ngrb
    LaTab{igrb} =   [ num2str(Zmodel.(Zmodel.ID{1}).data(igrb,1)) ...
                    , ' & ' ...
                    ...
                    , sprintf('%.2f',round(Zmodel.(Zmodel.ID{1}).data(igrb,2),2)) ...
                    , ' & $[' ...
                    , sprintf('%.2f',round(Zmodel.(Zmodel.ID{1}).data(igrb,4),2)) ...
                    , ' , ' ...
                    , sprintf('%.2f',round(Zmodel.(Zmodel.ID{1}).data(igrb,8),2)) ...
                    , ']$ & ' ...
                    ...
                    , sprintf('%.2f',round(Zmodel.(Zmodel.ID{2}).data(igrb,2),2)) ...
                    , ' & $[' ...
                    , sprintf('%.2f',round(Zmodel.(Zmodel.ID{2}).data(igrb,4),2)) ...
                    , ' , ' ...
                    , sprintf('%.2f',round(Zmodel.(Zmodel.ID{2}).data(igrb,8),2)) ...
                    , ']$ & ' ...
                    ...
                    , sprintf('%.2f',round(Zmodel.(Zmodel.ID{3}).data(igrb,2),2)) ...
                    , ' & $[' ...
                    , sprintf('%.2f',round(Zmodel.(Zmodel.ID{3}).data(igrb,4),2)) ...
                    , ' , ' ...
                    , sprintf('%.2f',round(Zmodel.(Zmodel.ID{3}).data(igrb,8),2)) ...
                    , ']$ & ' ...
                    ...
                    , sprintf('%.2f',round(Zmodel.(Zmodel.ID{4}).data(igrb,2),2)) ...
                    , ' & $[' ...
                    , sprintf('%.2f',round(Zmodel.(Zmodel.ID{4}).data(igrb,4),2)) ...
                    , ' , ' ...
                    , sprintf('%.2f',round(Zmodel.(Zmodel.ID{4}).data(igrb,8),2)) ...
                    , ']$ \\ [0.5ex]' ...
                    ];
end

% write to output file
fid = fopen(fullfile(outDir,"tabRedshiftCatalogContents.tex"),"w");
fprintf(fid,'%s\n',LaTab{:});
fclose(fid);
